<ul class="nav nav-tabs nav-stacked">
    <?php foreach($menu as $m): ?>
        <?php if(isset($id)): ?>
            <?php $_style='active'; ?>
        <?php else: ?>
            <?php $_style=''; ?>
        <?php endif; ?>
        <li class="<?php echo $_style; ?>">
            <a href="<?php echo $m['enalce']; ?>"><i class="<?php echo $m['imagen']; ?>"></i> <?php echo $m['totulo']; ?></a>
        </li>
    <?php endforeach; ?>
</ul>

<?php // print_r($menu); ?>